// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace FashionStore.Infrastructure.Data.Identity.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class InitIdentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitIdentity));
        
        string IMigrationMetadata.Id
        {
            get { return "201510261502355_InitIdentity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
